// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"time"
)

type DeliveryserviceServer struct {
	Deliveryservice int64     `db:"deliveryservice" json:"deliveryservice"`
	Server          int64     `db:"server" json:"server"`
	LastUpdated     time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleDeliveryserviceServer(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getDeliveryserviceServer(id)
	} else if method == "POST" {
		return postDeliveryserviceServer(payload)
	} else if method == "PUT" {
		return putDeliveryserviceServer(id, payload)
	} else if method == "DELETE" {
		return delDeliveryserviceServer(id)
	}
	return nil, nil
}

func getDeliveryserviceServer(id int) (interface{}, error) {
	if id >= 0 {
		return getDeliveryserviceServerById(id)
	} else {
		return getDeliveryserviceServers()
	}
}

// @Title getDeliveryserviceServerById
// @Description retrieves the deliveryservice_server information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    DeliveryserviceServer
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_server/{id} [get]
func getDeliveryserviceServerById(id int) (interface{}, error) {
	return genericGetById(id, "deliveryservice_server", (*DeliveryserviceServer)(nil))
}

// @Title getDeliveryserviceServers
// @Description retrieves the deliveryservice_server information for a certain id
// @Accept  application/json
// @Success 200 {array}    DeliveryserviceServer
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_server [get]
func getDeliveryserviceServers() (interface{}, error) {
	return genericGet("deliveryservice_server", (*DeliveryserviceServer)(nil))
}

// @Title postDeliveryserviceServer
// @Description enter a new deliveryservice_server
// @Accept  application/json
// @Param      Deliveryservice json      int64   false "deliveryservice description"
// @Param               Server json      int64   false "server description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_server [post]
func postDeliveryserviceServer(payload []byte) (interface{}, error) {
	return genericPost(payload, "deliveryservice_server", (*DeliveryserviceServer)(nil))
}

// @Title putDeliveryserviceServer
// @Description modify an existing deliveryservice_serverentry
// @Accept  application/json
// @Param      Deliveryservice json      int64   false "deliveryservice description"
// @Param               Server json      int64   false "server description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_server [put]
func putDeliveryserviceServer(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "deliveryservice_server", (*DeliveryserviceServer)(nil))
}

// @Title delDeliveryserviceServerById
// @Description deletes deliveryservice_server information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    DeliveryserviceServer
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_server/{id} [delete]
func delDeliveryserviceServer(id int) (interface{}, error) {
	return genericDelete(id, "deliveryservice_server")
}
