// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type Deliveryservice struct {
	Id                   int64       `db:"id" json:"id"`
	XmlId                string      `db:"xml_id" json:"xmlId"`
	Active               int64       `db:"active" json:"active"`
	Dscp                 int64       `db:"dscp" json:"dscp"`
	Signed               null.Int    `db:"signed" json:"signed"`
	QstringIgnore        null.Int    `db:"qstring_ignore" json:"qstringIgnore"`
	GeoLimit             null.Int    `db:"geo_limit" json:"geoLimit"`
	HttpBypassFqdn       null.String `db:"http_bypass_fqdn" json:"httpBypassFqdn"`
	DnsBypassIp          null.String `db:"dns_bypass_ip" json:"dnsBypassIp"`
	DnsBypassIp6         null.String `db:"dns_bypass_ip6" json:"dnsBypassIp6"`
	DnsBypassTtl         null.Int    `db:"dns_bypass_ttl" json:"dnsBypassTtl"`
	OrgServerFqdn        null.String `db:"org_server_fqdn" json:"orgServerFqdn"`
	Type                 int64       `db:"type" json:"type"`
	Profile              int64       `db:"profile" json:"profile"`
	CdnId                null.Int    `db:"cdn_id" json:"cdnId"`
	CcrDnsTtl            null.Int    `db:"ccr_dns_ttl" json:"ccrDnsTtl"`
	GlobalMaxMbps        null.Int    `db:"global_max_mbps" json:"globalMaxMbps"`
	GlobalMaxTps         null.Int    `db:"global_max_tps" json:"globalMaxTps"`
	LongDesc             null.String `db:"long_desc" json:"longDesc"`
	LongDesc1            null.String `db:"long_desc_1" json:"longDesc1"`
	LongDesc2            null.String `db:"long_desc_2" json:"longDesc2"`
	MaxDnsAnswers        null.Int    `db:"max_dns_answers" json:"maxDnsAnswers"`
	InfoUrl              null.String `db:"info_url" json:"infoUrl"`
	MissLat              null.Float  `db:"miss_lat" json:"missLat"`
	MissLong             null.Float  `db:"miss_long" json:"missLong"`
	CheckPath            null.String `db:"check_path" json:"checkPath"`
	LastUpdated          time.Time   `db:"last_updated" json:"lastUpdated"`
	Protocol             null.Int    `db:"protocol" json:"protocol"`
	SslKeyVersion        null.Int    `db:"ssl_key_version" json:"sslKeyVersion"`
	Ipv6RoutingEnabled   null.Int    `db:"ipv6_routing_enabled" json:"ipv6RoutingEnabled"`
	RangeRequestHandling null.Int    `db:"range_request_handling" json:"rangeRequestHandling"`
	EdgeHeaderRewrite    null.String `db:"edge_header_rewrite" json:"edgeHeaderRewrite"`
	OriginShield         null.String `db:"origin_shield" json:"originShield"`
	MidHeaderRewrite     null.String `db:"mid_header_rewrite" json:"midHeaderRewrite"`
	RegexRemap           null.String `db:"regex_remap" json:"regexRemap"`
	Cacheurl             null.String `db:"cacheurl" json:"cacheurl"`
	RemapText            null.String `db:"remap_text" json:"remapText"`
	MultiSiteOrigin      null.Int    `db:"multi_site_origin" json:"multiSiteOrigin"`
	DisplayName          string      `db:"display_name" json:"displayName"`
	TrResponseHeaders    null.String `db:"tr_response_headers" json:"trResponseHeaders"`
	InitialDispersion    null.Int    `db:"initial_dispersion" json:"initialDispersion"`
	DnsBypassCname       null.String `db:"dns_bypass_cname" json:"dnsBypassCname"`
}

func handleDeliveryservice(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getDeliveryservice(id)
	} else if method == "POST" {
		return postDeliveryservice(payload)
	} else if method == "PUT" {
		return putDeliveryservice(id, payload)
	} else if method == "DELETE" {
		return delDeliveryservice(id)
	}
	return nil, nil
}

func getDeliveryservice(id int) (interface{}, error) {
	if id >= 0 {
		return getDeliveryserviceById(id)
	} else {
		return getDeliveryservices()
	}
}

// @Title getDeliveryserviceById
// @Description retrieves the deliveryservice information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Deliveryservice
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice/{id} [get]
func getDeliveryserviceById(id int) (interface{}, error) {
	return genericGetById(id, "deliveryservice", (*Deliveryservice)(nil))
}

// @Title getDeliveryservices
// @Description retrieves the deliveryservice information for a certain id
// @Accept  application/json
// @Success 200 {array}    Deliveryservice
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice [get]
func getDeliveryservices() (interface{}, error) {
	return genericGet("deliveryservice", (*Deliveryservice)(nil))
}

// @Title postDeliveryservice
// @Description enter a new deliveryservice
// @Accept  application/json
// @Param                XmlId json     string   false "xml_id description"
// @Param               Active json      int64   false "active description"
// @Param                 Dscp json      int64   false "dscp description"
// @Param               Signed json        int    true "signed description"
// @Param        QstringIgnore json        int    true "qstring_ignore description"
// @Param             GeoLimit json        int    true "geo_limit description"
// @Param       HttpBypassFqdn json     string    true "http_bypass_fqdn description"
// @Param          DnsBypassIp json     string    true "dns_bypass_ip description"
// @Param         DnsBypassIp6 json     string    true "dns_bypass_ip6 description"
// @Param         DnsBypassTtl json        int    true "dns_bypass_ttl description"
// @Param        OrgServerFqdn json     string    true "org_server_fqdn description"
// @Param                 Type json      int64   false "type description"
// @Param              Profile json      int64   false "profile description"
// @Param                CdnId json        int    true "cdn_id description"
// @Param            CcrDnsTtl json        int    true "ccr_dns_ttl description"
// @Param        GlobalMaxMbps json        int    true "global_max_mbps description"
// @Param         GlobalMaxTps json        int    true "global_max_tps description"
// @Param             LongDesc json     string    true "long_desc description"
// @Param            LongDesc1 json     string    true "long_desc_1 description"
// @Param            LongDesc2 json     string    true "long_desc_2 description"
// @Param        MaxDnsAnswers json        int    true "max_dns_answers description"
// @Param              InfoUrl json     string    true "info_url description"
// @Param              MissLat json    float64    true "miss_lat description"
// @Param             MissLong json    float64    true "miss_long description"
// @Param            CheckPath json     string    true "check_path description"
// @Param             Protocol json        int    true "protocol description"
// @Param        SslKeyVersion json        int    true "ssl_key_version description"
// @Param   Ipv6RoutingEnabled json        int    true "ipv6_routing_enabled description"
// @Param RangeRequestHandling json        int    true "range_request_handling description"
// @Param    EdgeHeaderRewrite json     string    true "edge_header_rewrite description"
// @Param         OriginShield json     string    true "origin_shield description"
// @Param     MidHeaderRewrite json     string    true "mid_header_rewrite description"
// @Param           RegexRemap json     string    true "regex_remap description"
// @Param             Cacheurl json     string    true "cacheurl description"
// @Param            RemapText json     string    true "remap_text description"
// @Param      MultiSiteOrigin json        int    true "multi_site_origin description"
// @Param          DisplayName json     string   false "display_name description"
// @Param    TrResponseHeaders json     string    true "tr_response_headers description"
// @Param    InitialDispersion json        int    true "initial_dispersion description"
// @Param       DnsBypassCname json     string    true "dns_bypass_cname description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice [post]
func postDeliveryservice(payload []byte) (interface{}, error) {
	return genericPost(payload, "deliveryservice", (*Deliveryservice)(nil))
}

// @Title putDeliveryservice
// @Description modify an existing deliveryserviceentry
// @Accept  application/json
// @Param                XmlId json     string   false "xml_id description"
// @Param               Active json      int64   false "active description"
// @Param                 Dscp json      int64   false "dscp description"
// @Param               Signed json        int    true "signed description"
// @Param        QstringIgnore json        int    true "qstring_ignore description"
// @Param             GeoLimit json        int    true "geo_limit description"
// @Param       HttpBypassFqdn json     string    true "http_bypass_fqdn description"
// @Param          DnsBypassIp json     string    true "dns_bypass_ip description"
// @Param         DnsBypassIp6 json     string    true "dns_bypass_ip6 description"
// @Param         DnsBypassTtl json        int    true "dns_bypass_ttl description"
// @Param        OrgServerFqdn json     string    true "org_server_fqdn description"
// @Param                 Type json      int64   false "type description"
// @Param              Profile json      int64   false "profile description"
// @Param                CdnId json        int    true "cdn_id description"
// @Param            CcrDnsTtl json        int    true "ccr_dns_ttl description"
// @Param        GlobalMaxMbps json        int    true "global_max_mbps description"
// @Param         GlobalMaxTps json        int    true "global_max_tps description"
// @Param             LongDesc json     string    true "long_desc description"
// @Param            LongDesc1 json     string    true "long_desc_1 description"
// @Param            LongDesc2 json     string    true "long_desc_2 description"
// @Param        MaxDnsAnswers json        int    true "max_dns_answers description"
// @Param              InfoUrl json     string    true "info_url description"
// @Param              MissLat json    float64    true "miss_lat description"
// @Param             MissLong json    float64    true "miss_long description"
// @Param            CheckPath json     string    true "check_path description"
// @Param             Protocol json        int    true "protocol description"
// @Param        SslKeyVersion json        int    true "ssl_key_version description"
// @Param   Ipv6RoutingEnabled json        int    true "ipv6_routing_enabled description"
// @Param RangeRequestHandling json        int    true "range_request_handling description"
// @Param    EdgeHeaderRewrite json     string    true "edge_header_rewrite description"
// @Param         OriginShield json     string    true "origin_shield description"
// @Param     MidHeaderRewrite json     string    true "mid_header_rewrite description"
// @Param           RegexRemap json     string    true "regex_remap description"
// @Param             Cacheurl json     string    true "cacheurl description"
// @Param            RemapText json     string    true "remap_text description"
// @Param      MultiSiteOrigin json        int    true "multi_site_origin description"
// @Param          DisplayName json     string   false "display_name description"
// @Param    TrResponseHeaders json     string    true "tr_response_headers description"
// @Param    InitialDispersion json        int    true "initial_dispersion description"
// @Param       DnsBypassCname json     string    true "dns_bypass_cname description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice [put]
func putDeliveryservice(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "deliveryservice", (*Deliveryservice)(nil))
}

// @Title delDeliveryserviceById
// @Description deletes deliveryservice information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Deliveryservice
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice/{id} [delete]
func delDeliveryservice(id int) (interface{}, error) {
	return genericDelete(id, "deliveryservice")
}
