// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"time"
)

type DeliveryserviceTmuser struct {
	Deliveryservice int64     `db:"deliveryservice" json:"deliveryservice"`
	TmUserId        int64     `db:"tm_user_id" json:"tmUserId"`
	LastUpdated     time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleDeliveryserviceTmuser(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getDeliveryserviceTmuser(id)
	} else if method == "POST" {
		return postDeliveryserviceTmuser(payload)
	} else if method == "PUT" {
		return putDeliveryserviceTmuser(id, payload)
	} else if method == "DELETE" {
		return delDeliveryserviceTmuser(id)
	}
	return nil, nil
}

func getDeliveryserviceTmuser(id int) (interface{}, error) {
	if id >= 0 {
		return getDeliveryserviceTmuserById(id)
	} else {
		return getDeliveryserviceTmusers()
	}
}

// @Title getDeliveryserviceTmuserById
// @Description retrieves the deliveryservice_tmuser information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    DeliveryserviceTmuser
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_tmuser/{id} [get]
func getDeliveryserviceTmuserById(id int) (interface{}, error) {
	return genericGetById(id, "deliveryservice_tmuser", (*DeliveryserviceTmuser)(nil))
}

// @Title getDeliveryserviceTmusers
// @Description retrieves the deliveryservice_tmuser information for a certain id
// @Accept  application/json
// @Success 200 {array}    DeliveryserviceTmuser
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_tmuser [get]
func getDeliveryserviceTmusers() (interface{}, error) {
	return genericGet("deliveryservice_tmuser", (*DeliveryserviceTmuser)(nil))
}

// @Title postDeliveryserviceTmuser
// @Description enter a new deliveryservice_tmuser
// @Accept  application/json
// @Param      Deliveryservice json      int64   false "deliveryservice description"
// @Param             TmUserId json      int64   false "tm_user_id description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_tmuser [post]
func postDeliveryserviceTmuser(payload []byte) (interface{}, error) {
	return genericPost(payload, "deliveryservice_tmuser", (*DeliveryserviceTmuser)(nil))
}

// @Title putDeliveryserviceTmuser
// @Description modify an existing deliveryservice_tmuserentry
// @Accept  application/json
// @Param      Deliveryservice json      int64   false "deliveryservice description"
// @Param             TmUserId json      int64   false "tm_user_id description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_tmuser [put]
func putDeliveryserviceTmuser(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "deliveryservice_tmuser", (*DeliveryserviceTmuser)(nil))
}

// @Title delDeliveryserviceTmuserById
// @Description deletes deliveryservice_tmuser information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    DeliveryserviceTmuser
// @Resource /api/2.0
// @Router /api/2.0/deliveryservice_tmuser/{id} [delete]
func delDeliveryserviceTmuser(id int) (interface{}, error) {
	return genericDelete(id, "deliveryservice_tmuser")
}
