// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"time"
)

type FederationTmuser struct {
	Federation  int64     `db:"federation" json:"federation"`
	TmUser      int64     `db:"tm_user" json:"tmUser"`
	Role        int64     `db:"role" json:"role"`
	LastUpdated time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleFederationTmuser(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getFederationTmuser(id)
	} else if method == "POST" {
		return postFederationTmuser(payload)
	} else if method == "PUT" {
		return putFederationTmuser(id, payload)
	} else if method == "DELETE" {
		return delFederationTmuser(id)
	}
	return nil, nil
}

func getFederationTmuser(id int) (interface{}, error) {
	if id >= 0 {
		return getFederationTmuserById(id)
	} else {
		return getFederationTmusers()
	}
}

// @Title getFederationTmuserById
// @Description retrieves the federation_tmuser information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    FederationTmuser
// @Resource /api/2.0
// @Router /api/2.0/federation_tmuser/{id} [get]
func getFederationTmuserById(id int) (interface{}, error) {
	return genericGetById(id, "federation_tmuser", (*FederationTmuser)(nil))
}

// @Title getFederationTmusers
// @Description retrieves the federation_tmuser information for a certain id
// @Accept  application/json
// @Success 200 {array}    FederationTmuser
// @Resource /api/2.0
// @Router /api/2.0/federation_tmuser [get]
func getFederationTmusers() (interface{}, error) {
	return genericGet("federation_tmuser", (*FederationTmuser)(nil))
}

// @Title postFederationTmuser
// @Description enter a new federation_tmuser
// @Accept  application/json
// @Param           Federation json      int64   false "federation description"
// @Param               TmUser json      int64   false "tm_user description"
// @Param                 Role json      int64   false "role description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation_tmuser [post]
func postFederationTmuser(payload []byte) (interface{}, error) {
	return genericPost(payload, "federation_tmuser", (*FederationTmuser)(nil))
}

// @Title putFederationTmuser
// @Description modify an existing federation_tmuserentry
// @Accept  application/json
// @Param           Federation json      int64   false "federation description"
// @Param               TmUser json      int64   false "tm_user description"
// @Param                 Role json      int64   false "role description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation_tmuser [put]
func putFederationTmuser(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "federation_tmuser", (*FederationTmuser)(nil))
}

// @Title delFederationTmuserById
// @Description deletes federation_tmuser information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    FederationTmuser
// @Resource /api/2.0
// @Router /api/2.0/federation_tmuser/{id} [delete]
func delFederationTmuser(id int) (interface{}, error) {
	return genericDelete(id, "federation_tmuser")
}
