// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"time"
)

type FederationResolver struct {
	Id          int64     `db:"id" json:"id"`
	IpAddress   string    `db:"ip_address" json:"ipAddress"`
	Type        int64     `db:"type" json:"type"`
	LastUpdated time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleFederationResolver(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getFederationResolver(id)
	} else if method == "POST" {
		return postFederationResolver(payload)
	} else if method == "PUT" {
		return putFederationResolver(id, payload)
	} else if method == "DELETE" {
		return delFederationResolver(id)
	}
	return nil, nil
}

func getFederationResolver(id int) (interface{}, error) {
	if id >= 0 {
		return getFederationResolverById(id)
	} else {
		return getFederationResolvers()
	}
}

// @Title getFederationResolverById
// @Description retrieves the federation_resolver information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    FederationResolver
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver/{id} [get]
func getFederationResolverById(id int) (interface{}, error) {
	return genericGetById(id, "federation_resolver", (*FederationResolver)(nil))
}

// @Title getFederationResolvers
// @Description retrieves the federation_resolver information for a certain id
// @Accept  application/json
// @Success 200 {array}    FederationResolver
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver [get]
func getFederationResolvers() (interface{}, error) {
	return genericGet("federation_resolver", (*FederationResolver)(nil))
}

// @Title postFederationResolver
// @Description enter a new federation_resolver
// @Accept  application/json
// @Param            IpAddress json     string   false "ip_address description"
// @Param                 Type json      int64   false "type description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver [post]
func postFederationResolver(payload []byte) (interface{}, error) {
	return genericPost(payload, "federation_resolver", (*FederationResolver)(nil))
}

// @Title putFederationResolver
// @Description modify an existing federation_resolverentry
// @Accept  application/json
// @Param            IpAddress json     string   false "ip_address description"
// @Param                 Type json      int64   false "type description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver [put]
func putFederationResolver(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "federation_resolver", (*FederationResolver)(nil))
}

// @Title delFederationResolverById
// @Description deletes federation_resolver information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    FederationResolver
// @Resource /api/2.0
// @Router /api/2.0/federation_resolver/{id} [delete]
func delFederationResolver(id int) (interface{}, error) {
	return genericDelete(id, "federation_resolver")
}
