// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	"time"
)

type GooseDbVersion struct {
	Id        int64     `db:"id" json:"id"`
	VersionId int64     `db:"version_id" json:"versionId"`
	IsApplied int64     `db:"is_applied" json:"isApplied"`
	Tstamp    time.Time `db:"tstamp" json:"tstamp"`
}

func handleGooseDbVersion(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getGooseDbVersion(id)
	} else if method == "POST" {
		return postGooseDbVersion(payload)
	} else if method == "PUT" {
		return putGooseDbVersion(id, payload)
	} else if method == "DELETE" {
		return delGooseDbVersion(id)
	}
	return nil, nil
}

func getGooseDbVersion(id int) (interface{}, error) {
	if id >= 0 {
		return getGooseDbVersionById(id)
	} else {
		return getGooseDbVersions()
	}
}

// @Title getGooseDbVersionById
// @Description retrieves the goose_db_version information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    GooseDbVersion
// @Resource /api/2.0
// @Router /api/2.0/goose_db_version/{id} [get]
func getGooseDbVersionById(id int) (interface{}, error) {
	return genericGetById(id, "goose_db_version", (*GooseDbVersion)(nil))
}

// @Title getGooseDbVersions
// @Description retrieves the goose_db_version information for a certain id
// @Accept  application/json
// @Success 200 {array}    GooseDbVersion
// @Resource /api/2.0
// @Router /api/2.0/goose_db_version [get]
func getGooseDbVersions() (interface{}, error) {
	return genericGet("goose_db_version", (*GooseDbVersion)(nil))
}

// @Title postGooseDbVersion
// @Description enter a new goose_db_version
// @Accept  application/json
// @Param            VersionId json      int64   false "version_id description"
// @Param            IsApplied json      int64   false "is_applied description"
// @Param               Tstamp json  time.Time    true "tstamp description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/goose_db_version [post]
func postGooseDbVersion(payload []byte) (interface{}, error) {
	return genericPost(payload, "goose_db_version", (*GooseDbVersion)(nil))
}

// @Title putGooseDbVersion
// @Description modify an existing goose_db_versionentry
// @Accept  application/json
// @Param            VersionId json      int64   false "version_id description"
// @Param            IsApplied json      int64   false "is_applied description"
// @Param               Tstamp json  time.Time    true "tstamp description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/goose_db_version [put]
func putGooseDbVersion(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "goose_db_version", (*GooseDbVersion)(nil))
}

// @Title delGooseDbVersionById
// @Description deletes goose_db_version information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    GooseDbVersion
// @Resource /api/2.0
// @Router /api/2.0/goose_db_version/{id} [delete]
func delGooseDbVersion(id int) (interface{}, error) {
	return genericDelete(id, "goose_db_version")
}
