// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type Job struct {
	Id                 int64       `db:"id" json:"id"`
	Agent              null.Int    `db:"agent" json:"agent"`
	ObjectType         null.String `db:"object_type" json:"objectType"`
	ObjectName         null.String `db:"object_name" json:"objectName"`
	Keyword            string      `db:"keyword" json:"keyword"`
	Parameters         null.String `db:"parameters" json:"parameters"`
	AssetUrl           string      `db:"asset_url" json:"assetUrl"`
	AssetType          string      `db:"asset_type" json:"assetType"`
	Status             int64       `db:"status" json:"status"`
	StartTime          time.Time   `db:"start_time" json:"startTime"`
	EnteredTime        time.Time   `db:"entered_time" json:"enteredTime"`
	JobUser            int64       `db:"job_user" json:"jobUser"`
	LastUpdated        time.Time   `db:"last_updated" json:"lastUpdated"`
	JobDeliveryservice null.Int    `db:"job_deliveryservice" json:"jobDeliveryservice"`
}

func handleJob(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getJob(id)
	} else if method == "POST" {
		return postJob(payload)
	} else if method == "PUT" {
		return putJob(id, payload)
	} else if method == "DELETE" {
		return delJob(id)
	}
	return nil, nil
}

func getJob(id int) (interface{}, error) {
	if id >= 0 {
		return getJobById(id)
	} else {
		return getJobs()
	}
}

// @Title getJobById
// @Description retrieves the job information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Job
// @Resource /api/2.0
// @Router /api/2.0/job/{id} [get]
func getJobById(id int) (interface{}, error) {
	return genericGetById(id, "job", (*Job)(nil))
}

// @Title getJobs
// @Description retrieves the job information for a certain id
// @Accept  application/json
// @Success 200 {array}    Job
// @Resource /api/2.0
// @Router /api/2.0/job [get]
func getJobs() (interface{}, error) {
	return genericGet("job", (*Job)(nil))
}

// @Title postJob
// @Description enter a new job
// @Accept  application/json
// @Param                Agent json        int    true "agent description"
// @Param           ObjectType json     string    true "object_type description"
// @Param           ObjectName json     string    true "object_name description"
// @Param              Keyword json     string   false "keyword description"
// @Param           Parameters json     string    true "parameters description"
// @Param             AssetUrl json     string   false "asset_url description"
// @Param            AssetType json     string   false "asset_type description"
// @Param               Status json      int64   false "status description"
// @Param            StartTime json  time.Time   false "start_time description"
// @Param          EnteredTime json  time.Time   false "entered_time description"
// @Param              JobUser json      int64   false "job_user description"
// @Param   JobDeliveryservice json        int    true "job_deliveryservice description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job [post]
func postJob(payload []byte) (interface{}, error) {
	return genericPost(payload, "job", (*Job)(nil))
}

// @Title putJob
// @Description modify an existing jobentry
// @Accept  application/json
// @Param                Agent json        int    true "agent description"
// @Param           ObjectType json     string    true "object_type description"
// @Param           ObjectName json     string    true "object_name description"
// @Param              Keyword json     string   false "keyword description"
// @Param           Parameters json     string    true "parameters description"
// @Param             AssetUrl json     string   false "asset_url description"
// @Param            AssetType json     string   false "asset_type description"
// @Param               Status json      int64   false "status description"
// @Param            StartTime json  time.Time   false "start_time description"
// @Param          EnteredTime json  time.Time   false "entered_time description"
// @Param              JobUser json      int64   false "job_user description"
// @Param   JobDeliveryservice json        int    true "job_deliveryservice description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job [put]
func putJob(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "job", (*Job)(nil))
}

// @Title delJobById
// @Description deletes job information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Job
// @Resource /api/2.0
// @Router /api/2.0/job/{id} [delete]
func delJob(id int) (interface{}, error) {
	return genericDelete(id, "job")
}
