// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type JobStatus struct {
	Id          int64       `db:"id" json:"id"`
	Name        null.String `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
	LastUpdated time.Time   `db:"last_updated" json:"lastUpdated"`
}

func handleJobStatus(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getJobStatus(id)
	} else if method == "POST" {
		return postJobStatus(payload)
	} else if method == "PUT" {
		return putJobStatus(id, payload)
	} else if method == "DELETE" {
		return delJobStatus(id)
	}
	return nil, nil
}

func getJobStatus(id int) (interface{}, error) {
	if id >= 0 {
		return getJobStatusById(id)
	} else {
		return getJobStatuss()
	}
}

// @Title getJobStatusById
// @Description retrieves the job_status information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    JobStatus
// @Resource /api/2.0
// @Router /api/2.0/job_status/{id} [get]
func getJobStatusById(id int) (interface{}, error) {
	return genericGetById(id, "job_status", (*JobStatus)(nil))
}

// @Title getJobStatuss
// @Description retrieves the job_status information for a certain id
// @Accept  application/json
// @Success 200 {array}    JobStatus
// @Resource /api/2.0
// @Router /api/2.0/job_status [get]
func getJobStatuss() (interface{}, error) {
	return genericGet("job_status", (*JobStatus)(nil))
}

// @Title postJobStatus
// @Description enter a new job_status
// @Accept  application/json
// @Param                 Name json     string    true "name description"
// @Param          Description json     string    true "description description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job_status [post]
func postJobStatus(payload []byte) (interface{}, error) {
	return genericPost(payload, "job_status", (*JobStatus)(nil))
}

// @Title putJobStatus
// @Description modify an existing job_statusentry
// @Accept  application/json
// @Param                 Name json     string    true "name description"
// @Param          Description json     string    true "description description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job_status [put]
func putJobStatus(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "job_status", (*JobStatus)(nil))
}

// @Title delJobStatusById
// @Description deletes job_status information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    JobStatus
// @Resource /api/2.0
// @Router /api/2.0/job_status/{id} [delete]
func delJobStatus(id int) (interface{}, error) {
	return genericDelete(id, "job_status")
}
