// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type JobAgent struct {
	Id          int64       `db:"id" json:"id"`
	Name        null.String `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
	Active      int64       `db:"active" json:"active"`
	LastUpdated time.Time   `db:"last_updated" json:"lastUpdated"`
}

func handleJobAgent(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getJobAgent(id)
	} else if method == "POST" {
		return postJobAgent(payload)
	} else if method == "PUT" {
		return putJobAgent(id, payload)
	} else if method == "DELETE" {
		return delJobAgent(id)
	}
	return nil, nil
}

func getJobAgent(id int) (interface{}, error) {
	if id >= 0 {
		return getJobAgentById(id)
	} else {
		return getJobAgents()
	}
}

// @Title getJobAgentById
// @Description retrieves the job_agent information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    JobAgent
// @Resource /api/2.0
// @Router /api/2.0/job_agent/{id} [get]
func getJobAgentById(id int) (interface{}, error) {
	return genericGetById(id, "job_agent", (*JobAgent)(nil))
}

// @Title getJobAgents
// @Description retrieves the job_agent information for a certain id
// @Accept  application/json
// @Success 200 {array}    JobAgent
// @Resource /api/2.0
// @Router /api/2.0/job_agent [get]
func getJobAgents() (interface{}, error) {
	return genericGet("job_agent", (*JobAgent)(nil))
}

// @Title postJobAgent
// @Description enter a new job_agent
// @Accept  application/json
// @Param                 Name json     string    true "name description"
// @Param          Description json     string    true "description description"
// @Param               Active json      int64   false "active description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job_agent [post]
func postJobAgent(payload []byte) (interface{}, error) {
	return genericPost(payload, "job_agent", (*JobAgent)(nil))
}

// @Title putJobAgent
// @Description modify an existing job_agententry
// @Accept  application/json
// @Param                 Name json     string    true "name description"
// @Param          Description json     string    true "description description"
// @Param               Active json      int64   false "active description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/job_agent [put]
func putJobAgent(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "job_agent", (*JobAgent)(nil))
}

// @Title delJobAgentById
// @Description deletes job_agent information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    JobAgent
// @Resource /api/2.0
// @Router /api/2.0/job_agent/{id} [delete]
func delJobAgent(id int) (interface{}, error) {
	return genericDelete(id, "job_agent")
}
