// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type Servercheck struct {
	Id          int64     `db:"id" json:"id"`
	Server      int64     `db:"server" json:"server"`
	Aa          null.Int  `db:"aa" json:"aa"`
	Ab          null.Int  `db:"ab" json:"ab"`
	Ac          null.Int  `db:"ac" json:"ac"`
	Ad          null.Int  `db:"ad" json:"ad"`
	Ae          null.Int  `db:"ae" json:"ae"`
	Af          null.Int  `db:"af" json:"af"`
	Ag          null.Int  `db:"ag" json:"ag"`
	Ah          null.Int  `db:"ah" json:"ah"`
	Ai          null.Int  `db:"ai" json:"ai"`
	Aj          null.Int  `db:"aj" json:"aj"`
	Ak          null.Int  `db:"ak" json:"ak"`
	Al          null.Int  `db:"al" json:"al"`
	Am          null.Int  `db:"am" json:"am"`
	An          null.Int  `db:"an" json:"an"`
	Ao          null.Int  `db:"ao" json:"ao"`
	Ap          null.Int  `db:"ap" json:"ap"`
	Aq          null.Int  `db:"aq" json:"aq"`
	Ar          null.Int  `db:"ar" json:"ar"`
	As          null.Int  `db:"as" json:"as"`
	At          null.Int  `db:"at" json:"at"`
	Au          null.Int  `db:"au" json:"au"`
	Av          null.Int  `db:"av" json:"av"`
	Aw          null.Int  `db:"aw" json:"aw"`
	Ax          null.Int  `db:"ax" json:"ax"`
	Ay          null.Int  `db:"ay" json:"ay"`
	Az          null.Int  `db:"az" json:"az"`
	Ba          null.Int  `db:"ba" json:"ba"`
	Bb          null.Int  `db:"bb" json:"bb"`
	Bc          null.Int  `db:"bc" json:"bc"`
	Bd          null.Int  `db:"bd" json:"bd"`
	Be          null.Int  `db:"be" json:"be"`
	LastUpdated time.Time `db:"last_updated" json:"lastUpdated"`
}

func handleServercheck(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getServercheck(id)
	} else if method == "POST" {
		return postServercheck(payload)
	} else if method == "PUT" {
		return putServercheck(id, payload)
	} else if method == "DELETE" {
		return delServercheck(id)
	}
	return nil, nil
}

func getServercheck(id int) (interface{}, error) {
	if id >= 0 {
		return getServercheckById(id)
	} else {
		return getServerchecks()
	}
}

// @Title getServercheckById
// @Description retrieves the servercheck information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Servercheck
// @Resource /api/2.0
// @Router /api/2.0/servercheck/{id} [get]
func getServercheckById(id int) (interface{}, error) {
	return genericGetById(id, "servercheck", (*Servercheck)(nil))
}

// @Title getServerchecks
// @Description retrieves the servercheck information for a certain id
// @Accept  application/json
// @Success 200 {array}    Servercheck
// @Resource /api/2.0
// @Router /api/2.0/servercheck [get]
func getServerchecks() (interface{}, error) {
	return genericGet("servercheck", (*Servercheck)(nil))
}

// @Title postServercheck
// @Description enter a new servercheck
// @Accept  application/json
// @Param               Server json      int64   false "server description"
// @Param                   Aa json        int    true "aa description"
// @Param                   Ab json        int    true "ab description"
// @Param                   Ac json        int    true "ac description"
// @Param                   Ad json        int    true "ad description"
// @Param                   Ae json        int    true "ae description"
// @Param                   Af json        int    true "af description"
// @Param                   Ag json        int    true "ag description"
// @Param                   Ah json        int    true "ah description"
// @Param                   Ai json        int    true "ai description"
// @Param                   Aj json        int    true "aj description"
// @Param                   Ak json        int    true "ak description"
// @Param                   Al json        int    true "al description"
// @Param                   Am json        int    true "am description"
// @Param                   An json        int    true "an description"
// @Param                   Ao json        int    true "ao description"
// @Param                   Ap json        int    true "ap description"
// @Param                   Aq json        int    true "aq description"
// @Param                   Ar json        int    true "ar description"
// @Param                   As json        int    true "as description"
// @Param                   At json        int    true "at description"
// @Param                   Au json        int    true "au description"
// @Param                   Av json        int    true "av description"
// @Param                   Aw json        int    true "aw description"
// @Param                   Ax json        int    true "ax description"
// @Param                   Ay json        int    true "ay description"
// @Param                   Az json        int    true "az description"
// @Param                   Ba json        int    true "ba description"
// @Param                   Bb json        int    true "bb description"
// @Param                   Bc json        int    true "bc description"
// @Param                   Bd json        int    true "bd description"
// @Param                   Be json        int    true "be description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/servercheck [post]
func postServercheck(payload []byte) (interface{}, error) {
	return genericPost(payload, "servercheck", (*Servercheck)(nil))
}

// @Title putServercheck
// @Description modify an existing servercheckentry
// @Accept  application/json
// @Param               Server json      int64   false "server description"
// @Param                   Aa json        int    true "aa description"
// @Param                   Ab json        int    true "ab description"
// @Param                   Ac json        int    true "ac description"
// @Param                   Ad json        int    true "ad description"
// @Param                   Ae json        int    true "ae description"
// @Param                   Af json        int    true "af description"
// @Param                   Ag json        int    true "ag description"
// @Param                   Ah json        int    true "ah description"
// @Param                   Ai json        int    true "ai description"
// @Param                   Aj json        int    true "aj description"
// @Param                   Ak json        int    true "ak description"
// @Param                   Al json        int    true "al description"
// @Param                   Am json        int    true "am description"
// @Param                   An json        int    true "an description"
// @Param                   Ao json        int    true "ao description"
// @Param                   Ap json        int    true "ap description"
// @Param                   Aq json        int    true "aq description"
// @Param                   Ar json        int    true "ar description"
// @Param                   As json        int    true "as description"
// @Param                   At json        int    true "at description"
// @Param                   Au json        int    true "au description"
// @Param                   Av json        int    true "av description"
// @Param                   Aw json        int    true "aw description"
// @Param                   Ax json        int    true "ax description"
// @Param                   Ay json        int    true "ay description"
// @Param                   Az json        int    true "az description"
// @Param                   Ba json        int    true "ba description"
// @Param                   Bb json        int    true "bb description"
// @Param                   Bc json        int    true "bc description"
// @Param                   Bd json        int    true "bd description"
// @Param                   Be json        int    true "be description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/servercheck [put]
func putServercheck(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "servercheck", (*Servercheck)(nil))
}

// @Title delServercheckById
// @Description deletes servercheck information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Servercheck
// @Resource /api/2.0
// @Router /api/2.0/servercheck/{id} [delete]
func delServercheck(id int) (interface{}, error) {
	return genericDelete(id, "servercheck")
}
