// Copyright 2015 Comcast Cable Communications Management, LLC

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was initially generated by gen_goto2.go (add link), as a start
// of the Traffic Ops golang data model

package api

import (
	_ "github.com/Comcast/traffic_control/traffic_ops/goto2/output_format" // needed for swagger
	null "gopkg.in/guregu/null.v3"
	"time"
)

type Type struct {
	Id          int64       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
	UseInTable  null.String `db:"use_in_table" json:"useInTable"`
	LastUpdated time.Time   `db:"last_updated" json:"lastUpdated"`
}

func handleType(method string, id int, payload []byte) (interface{}, error) {
	if method == "GET" {
		return getType(id)
	} else if method == "POST" {
		return postType(payload)
	} else if method == "PUT" {
		return putType(id, payload)
	} else if method == "DELETE" {
		return delType(id)
	}
	return nil, nil
}

func getType(id int) (interface{}, error) {
	if id >= 0 {
		return getTypeById(id)
	} else {
		return getTypes()
	}
}

// @Title getTypeById
// @Description retrieves the type information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Type
// @Resource /api/2.0
// @Router /api/2.0/type/{id} [get]
func getTypeById(id int) (interface{}, error) {
	return genericGetById(id, "type", (*Type)(nil))
}

// @Title getTypes
// @Description retrieves the type information for a certain id
// @Accept  application/json
// @Success 200 {array}    Type
// @Resource /api/2.0
// @Router /api/2.0/type [get]
func getTypes() (interface{}, error) {
	return genericGet("type", (*Type)(nil))
}

// @Title postType
// @Description enter a new type
// @Accept  application/json
// @Param                 Name json     string   false "name description"
// @Param          Description json     string    true "description description"
// @Param           UseInTable json     string    true "use_in_table description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/type [post]
func postType(payload []byte) (interface{}, error) {
	return genericPost(payload, "type", (*Type)(nil))
}

// @Title putType
// @Description modify an existing typeentry
// @Accept  application/json
// @Param                 Name json     string   false "name description"
// @Param          Description json     string    true "description description"
// @Param           UseInTable json     string    true "use_in_table description"
// @Success 200 {object}    output_format.ApiWrapper
// @Resource /api/2.0
// @Router /api/2.0/type [put]
func putType(id int, payload []byte) (interface{}, error) {
	return genericPut(id, payload, "type", (*Type)(nil))
}

// @Title delTypeById
// @Description deletes type information for a certain id
// @Accept  application/json
// @Param   id              path    int     false        "The row id"
// @Success 200 {array}    Type
// @Resource /api/2.0
// @Router /api/2.0/type/{id} [delete]
func delType(id int) (interface{}, error) {
	return genericDelete(id, "type")
}
